name: Xcode - Build and Analyze

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    name: Build and analyse default scheme using xcodebuild command
    runs-on: macos-15

    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Show Xcode Path
        run: sudo xcode-select --print-path
      - name: Set Default Scheme
        run: |
          scheme_list=$(xcodebuild -list -json | tr -d "\n")
          default=$(echo $scheme_list | ruby -e "require 'json'; puts JSON.parse(STDIN.gets)['project']['targets'][0]")
          echo $default | cat >default
          echo Using default scheme: $default
      - name: Build
        env:
          scheme: Quis
        run: |
          scheme="Quis"

          if [ -f *.xcworkspace ]; then
            file_to_build=$(ls -1 *.xcworkspace | head -n1)
            filetype_param="-workspace"
          else
            file_to_build=$(ls -1 *.xcodeproj | head -n1)
            filetype_param="-project"
          fi

          if [ -z "$file_to_build" ]; then
            echo "❌ No .xcodeproj or .xcworkspace file found"
            exit 1
          fi

          destination=$(xcodebuild -showdestinations $filetype_param "$file_to_build" -scheme "$scheme" 2>/dev/null | \
            awk '/platform: macOS/ && /id:/{print $NF; exit}' | tr -d ' ')
          if [ -z "$destination" ]; then
            echo "❌ Could not determine a valid macOS destination"
            exit 1
          fi

          xcodebuild clean build analyze \
            $filetype_param "$file_to_build" \
            -scheme "$scheme" \
            -destination "id=$destination" | xcpretty
          exit ${PIPESTATUS[0]}
